services:
  postgres:
    image: postgres:17
    container_name: db-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
      TZ: Asia/Tokyo
    ports:
      - 5432:5432
    volumes:
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./postgres/init:/docker-entrypoint-initdb.d # 初期化用SQLファイル群置き場, imageの特性上コンテナ起動処理にディレクトリ内のSQLが実行される(データがある場合は実行されない)
      - pg_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]  # db起動コマンド

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: dbsql-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example1234.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  pg_data: