# -----------------------------
# Connection / Basic
# -----------------------------
listen_addresses = '*'
port = 5432
max_connections = 100

# -----------------------------
# Logging
# -----------------------------
logging_collector = on
log_destination = 'stderr'
log_directory = 'log'
log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'
log_line_prefix = '%m [%p] db=%d,user=%u,app=%a,client=%h '
log_statement = 'none'
log_min_duration_statement = 200   # 200ms以上を記録(遅いSQL用)

# -----------------------------
# Lock / Deadlock visibility
# -----------------------------
log_lock_waits = on
deadlock_timeout = '1s' # デッドロック判定

# -----------------------------
# Statistics extensions
# -----------------------------
shared_preload_libraries = 'pg_stat_statements,auto_explain'    # 拡張機能 pg_stat_statements... 実行統計を収集, auto_explain... 遅いSQLの実行計画をログ収集

# pg_stat_statements
pg_stat_statements.max = 10000
pg_stat_statements.track = all

# auto_explain (実行プランログ収集)
auto_explain.log_min_duration = '200ms'
auto_explain.log_analyze = on
auto_explain.log_buffers = on
auto_explain.log_timing = on
auto_explain.log_nested_statements = on

# -----------------------------
# Planner/IO helper (optional but useful)
# -----------------------------
track_io_timing = on

# -----------------------------
# Locale/Timezone
# -----------------------------
timezone = 'Asia/Tokyo'